// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmkap10ZiqOcWuXHkp9tUsWmRBpS3xSA',
    appId: '1:217635063922:web:357ed547f17c1ded411aeb',
    messagingSenderId: '217635063922',
    projectId: 'ciclocell-7ffc0',
    authDomain: 'ciclocell-7ffc0.firebaseapp.com',
    storageBucket: 'ciclocell-7ffc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0gbsrV5QQk3aasS9P09qFUbg7EWaip5w',
    appId: '1:217635063922:android:6a835ff30d3efacf411aeb',
    messagingSenderId: '217635063922',
    projectId: 'ciclocell-7ffc0',
    storageBucket: 'ciclocell-7ffc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYLhb3PpVi1oHMiVVhIsX-oSu-MWuiHsY',
    appId: '1:217635063922:ios:438b03b6de2be561411aeb',
    messagingSenderId: '217635063922',
    projectId: 'ciclocell-7ffc0',
    storageBucket: 'ciclocell-7ffc0.appspot.com',
    iosClientId: '217635063922-plr1p6ejif3rh9u3u48sppd0tha7dn30.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciclocell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYLhb3PpVi1oHMiVVhIsX-oSu-MWuiHsY',
    appId: '1:217635063922:ios:438b03b6de2be561411aeb',
    messagingSenderId: '217635063922',
    projectId: 'ciclocell-7ffc0',
    storageBucket: 'ciclocell-7ffc0.appspot.com',
    iosClientId: '217635063922-plr1p6ejif3rh9u3u48sppd0tha7dn30.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciclocell',
  );
}
