// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9uRTfaPWwKDciP3lYwxa9lYUNy4Ttk5A',
    appId: '1:553072605059:web:0658edb67a2e5b0339a8b6',
    messagingSenderId: '553072605059',
    projectId: 'ciclocell-d0a9e',
    authDomain: 'ciclocell-d0a9e.firebaseapp.com',
    storageBucket: 'ciclocell-d0a9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqd9UCvdBCBSfKupC1HfiyG4jUp0gWuKs',
    appId: '1:553072605059:android:4e2c12ee05d12d5639a8b6',
    messagingSenderId: '553072605059',
    projectId: 'ciclocell-d0a9e',
    storageBucket: 'ciclocell-d0a9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuWVqw-G92-0-r2I8B6QY3_j7bSD87LTA',
    appId: '1:553072605059:ios:47cf955113d88f4a39a8b6',
    messagingSenderId: '553072605059',
    projectId: 'ciclocell-d0a9e',
    storageBucket: 'ciclocell-d0a9e.appspot.com',
    iosClientId: '553072605059-ll0l5p5oc6dcdpnkv8jqr35krj1c79l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciclocell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuWVqw-G92-0-r2I8B6QY3_j7bSD87LTA',
    appId: '1:553072605059:ios:47cf955113d88f4a39a8b6',
    messagingSenderId: '553072605059',
    projectId: 'ciclocell-d0a9e',
    storageBucket: 'ciclocell-d0a9e.appspot.com',
    iosClientId: '553072605059-ll0l5p5oc6dcdpnkv8jqr35krj1c79l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ciclocell',
  );
}
